### ISSUE TITLE
支付宝当面付支付成功压根就不跳转

### ISSUE THREAD

**Issue by isyume** [zfaka-plus/zfaka#175]
这系统支付宝当面付有卵用啊！换了几台服务器，全是纯净系统装的，按照步骤一步步走，全TM付款成功不会跳转一直显示那二维码。搞个开源项目，还发卡系统，连支付都有问题，发个jB，让别人骗网友钱？人家付款了你TM不跳转？支付宝公钥，应用私钥，appid，三个参数填对了又如何？

别说我态度不好，别TM说什么爱用不用，TM搞开源就得有个开源的样，别什么垃圾产品都放上来，还上线宝塔一键部署呢。

花一天时间不停跟换系统，服务器每一个成功。艹。

看了下别的issue，早有人提出来，然并卵，根本没人理

**Comment by deepdream88** [comment]
额。。。运气差？我用宝塔一键部署用着挺好的，当面付正常，就是流程有点不恰当，我自己优化了一下，这个发卡系统应该是目前免费中最好的了。

功能确实还欠缺一些，不过作者也在开发2.0了。

作者只是懒得和这些垃圾吐槽较劲而已。

**Comment by AckyLin** [comment]
> 额。。。运气差？我用宝塔一键部署用着挺好的，当面付正常，就是流程有点不恰当，我自己优化了一下，这个发卡系统应该是目前免费中最好的了。
> 
> 功能确实还欠缺一些，不过作者也在开发2.0了。
> 
> 作者只是懒得和这些垃圾吐槽较劲而已。

你好，我接入了微信jsapi方式支付的方式，但是在回调的notify.php要处理订单逻辑的时候出了点问题，可否指点一下？

**Comment by hiyuanjie** [comment]
因为你的网站被墙了，所以无法连接支付宝

**Comment by hotket** [comment]
我的用宝塔搭建的，支付宝当面付也是支付了无法跳转，查询订单显示未支付，半个小时后再去查机能查到了，换了几个CDN都一样，现在在用CF CDN

**Comment by KLDGodY** [comment]
> 这系统支付宝当面付有卵用啊！换了几台服务器，全是纯净系统装的，按照步骤一步步走，全TM付款成功不会跳转一直显示那二维码。搞个开源项目，还发卡系统，连支付都有问题，发个jB，让别人骗网友钱？人家付款了你TM不跳转？支付宝公钥，应用私钥，appid，三个参数填对了又如何？
> 
> 别说我态度不好，别TM说什么爱用不用，TM搞开源就得有个开源的样，别什么垃圾产品都放上来，还上线宝塔一键部署呢。
> 
> 花一天时间不停跟换系统，服务器每一个成功。艹。
> 
> 看了下别的issue，早有人提出来，然并卵，根本没人理

pr 请

**Comment by KLDGodY** [comment]
> 这系统支付宝当面付有卵用啊！换了几台服务器，全是纯净系统装的，按照步骤一步步走，全TM付款成功不会跳转一直显示那二维码。搞个开源项目，还发卡系统，连支付都有问题，发个jB，让别人骗网友钱？人家付款了你TM不跳转？支付宝公钥，应用私钥，appid，三个参数填对了又如何？
> 
> 别说我态度不好，别TM说什么爱用不用，TM搞开源就得有个开源的样，别什么垃圾产品都放上来，还上线宝塔一键部署呢。
> 
> 花一天时间不停跟换系统，服务器每一个成功。艹。
> 
> 看了下别的issue，早有人提出来，然并卵，根本没人理

早有人提出来 没人理 那就自己谷歌学习 自己改源码
你认为垃圾 那么项目首页1.9k star哪里来的

**Comment by Beattheend** [comment]
diss

**Comment by nisngyo** [comment]
mjj第一发卡，自己不会用 怪别人？

**Comment by YukiCoco** [comment]
> 别说我态度不好，别TM说什么爱用不用，TM搞开源就得有个开源的样，别什么垃圾产品都放上来，还上线宝塔一键部署呢。

裂开，人家开源给你用就不错了，还得把你当大爷供着？爱用就用，不用就滚。

**Comment by kanadeblisst** [comment]
花钱买的产品是大爷是可以理解，在这用着开源的东西，不会用还这态度是真的脑残，别在这丢国人的脸。代码都给你了，有本事自己改源码去。

**Comment by tanst** [comment]
你是不是用的 Let's Encrypt 免费证书。
Let's Encrypt 更新了 R3 证书就不行了，建议更换其他证书，比如 cloudflare 证书。
