### ISSUE TITLE
bug提交--kami字段如果带引号会造成无法提取

### ISSUE THREAD

**Issue by Haoshenqi0123** [zfaka-plus/zfaka#178]
kami字段如果带引号会造成无法提取
[“123456”] 会报错要手动改成[123456] 彩能正常提取。
在ajax返回的字符串里是可以看到，只是解析成json的时候报错，建议对卡密字段中可能出现的特殊字符进行转义

**Comment by yumusb** [comment]
原来逻辑有编码问题。现在版本已经修改。
