### ISSUE TITLE
商品管理页面异常

### ISSUE THREAD

**Issue by cumtsd** [zfaka-plus/zfaka#181]
错误信息：数据接口请求异常
请求帮助，谢谢
![TIM截图20200318210800](https://user-images.githubusercontent.com/40632732/76963692-6889f200-695c-11ea-9e20-878293421f3e.jpg)

**Comment by KLDGodY** [comment]
检查防火墙

**Comment by cumtsd** [comment]
> 检查防火墙

跟那个没关系，bug，已经解决了

**Comment by KLDGodY** [comment]
> > 检查防火墙
> 
> 跟那个没关系，bug，已经解决了

ok

**Comment by 007ayong** [comment]
请问应该怎么处理，我也出现了

**Comment by chichu143** [comment]
> > 检查防火墙
> 
> 跟那个没关系，bug，已经解决了

请问这个是怎么解决的呢，我也出现了这个问题

**Comment by siemenstutorials** [comment]
> > > 检查防火墙
> > 
> > 
> > 跟那个没关系，bug，已经解决了
> 
> 请问这个是怎么解决的呢，我也出现了这个问题

同问如何解决这个问题？

**Comment by cumtsd** [comment]
> > > > 检查防火墙
> > > 
> > > 
> > > 跟那个没关系，bug，已经解决了
> > 
> > 
> > 请问这个是怎么解决的呢，我也出现了这个问题
> 
> 同问如何解决这个问题？

时间有点久远，忘记了，抱歉。大概是我修改了某个文件，然后我给改回去了。
是个bug
