### ISSUE TITLE
关于zfaka购买成功后销量数字不变动的问题

### ISSUE THREAD

**Issue by banana1024** [zfaka-plus/zfaka#186]
库存限制商品，购买成功后，库存减1，销量加1，但是不限制商品，购买成功后，销量不会自动加1。请问大家有这样的情况吗，重装好多次了，php版本和mysql版本也换了多个，现象一直存在。

**Comment by GitWgq** [comment]
最新版有这情况，

**Comment by KLDGodY** [comment]
PHP 7.1 MySQL 5.6 请
