### ISSUE TITLE
警告： 请按照安装要求配置yaf.use_namespace=1

### ISSUE THREAD

**Issue by luang87** [zfaka-plus/zfaka#206]
我已经配置啦，但是什么样配置都出现这个问题，有大佬可以帮忙下吗

我是用WIN+宝塔的。

**Comment by wuzhumeng** [comment]
我也是这个问题，没安装成功，宝塔升级版本了，这个教程还没有更新。

**Comment by dnslin** [comment]
在php的配置目录 添加一行就ok了

**Comment by wuzhumeng** [comment]
> 在php的配置目录添加一行就ok了

添加到哪个地方？
