### ISSUE TITLE
数据库迁移后无法正常使用

### ISSUE THREAD

**Issue by AH-dark** [zfaka-plus/zfaka#210]
前台所有操作显示【订单异常】，后台显示【更新失败】，求问怎么解决

**Comment by zkysimon** [comment]
我也遇到了，求问如何解决

**Comment by qinghuas** [comment]
可以参考这个issue
https://github.com/zlkbdotnet/zfaka/issues/159

**Comment by wngx99** [comment]
把表“order”里的text 类型的设默认值为 NULL
