### ISSUE TITLE
使用支付宝即时到账支付成功返回系统后，订单显示待支付

### ISSUE THREAD

**Issue by Madapang** [zfaka-plus/zfaka#233]
使用的支付接口是支付宝即时到账，在购买商品支付成功返回系统显示订单的页面，订单显示待支付，套不套CDN都一样。
下面是已经支付的订单，但是显示的都是待支付
![QQ截图20210615133055](https://user-images.githubusercontent.com/34815380/121998611-af27ff80-cdde-11eb-9584-3aad967e4e74.jpg)
![QQ截图20210615133205](https://user-images.githubusercontent.com/34815380/121998617-b0f1c300-cdde-11eb-816d-7011f1a756d6.jpg)

**Comment by skykain** [comment]
今天也遇到了这情况，换了个子域名之后恢复正常，感觉应该是支付宝那边将子域名拉入了黑名单

**Comment by Madapang** [comment]
> 今天也遇到了这情况，换了个子域名之后恢复正常，感觉应该是支付宝那边将子域名拉入了黑名单

要是拉黑的话，应该支付不会成功吧😨

**Comment by yumusb** [comment]
检查回调相关功能。尤其是https证书是否补全相关。
