### ISSUE TITLE
数据接口请求异常

### ISSUE THREAD

**Issue by siemenstutorials** [zfaka-plus/zfaka#238]
![image](https://user-images.githubusercontent.com/55917384/126238085-5bbb7eb7-1b36-402b-a666-e8f1688dcde4.png)
请问大佬这要如何解决？

**Comment by huiasd** [comment]
重新配置nginx后没有关闭 PATH_INFO

**Comment by siemenstutorials** [comment]
> 重新配置nginx后没有关闭 PATH_INFO

我先去试试 看下能不能解决问题
