### ISSUE TITLE
不兼容 PHP8

### ISSUE THREAD

**Issue by NPBeta** [zfaka-plus/zfaka#246]
直接上报错：
`
PHP Fatal error:  Uncaught Yaf\Exception\LoadFailed\View: Failed opening template zfaka/application/modules/Install/views/error/error.html: No such file or directory in /zfaka/public/index.php:12
Stack trace:
#0 zfaka/public/index.php(12): Yaf\Application->run()
#1 {main}
  thrown in zfaka/public/index.php on line 12
`
如果已经完成安装，则会报错各模板下无 error。
环境：PHP 8.0.10 / yaf 3.3.3 / Ubuntu 20.04.2 LTS x64
已确认 PHP 7.4.23 正常。

**Comment by NPBeta** [comment]
UPDATE：PHP8.0.10 + yaf3.3.0 报错，之前有误
PHP8.0.6 + yaf3.3.0 疑似正常

**Comment by NPBeta** [comment]
需要更多 PHP 和 yaf 版本组合测试具体原因

**Comment by NPBeta** [comment]
重新编译并测试，确认：
PHP 8.0.10 / yaf 3.3.3 -> 报错
PHP 7.4.23 / yaf 3.3.3 -> 正常
不太清楚 yaf + layui 架构的调试方法，因此似乎没发找到根本原因。可告知调试方法以便我进一步测试。

**Comment by yumusb** [comment]
那就用php7
