### ISSUE TITLE
码支付更新了接口，求开发者更新或者指点修改相应配置

### ISSUE THREAD

**Issue by knowledge-one** [zfaka-plus/zfaka#262]
码支付更新了api和相应请求格式，*本人水平实在有限* ，还请开发者大大可以指点如何修改相应文件适配新的码支付。

**码支付接口文档：** https://easydoc.net/doc/71721565/TcZNWhSq/PwS7nzvX

搜索了一下似乎是要修改`application/library/Pay/codepayalipay`下的`codepayalipay.php`文件，希望开发者大神可以抽空更新一下该文件。

**Comment by wngx99** [comment]
这是不是就是易支付？

**Comment by knowledge-one** [comment]
似乎是的，官方说兼容99%以上的易支付配置，然后给的接口文档就是上述链接 @wngx99

**Comment by knowledge-one** [comment]
就是易支付，他们给的[SDK](https://www.codepay.net/index/index/work.html)里面注释内容就是彩虹易支付～ 不过确实能力有限，不会改现有的zfaka配置 @wngx99

**Comment by knowledge-one** [comment]
您好，非常感谢您的这个问题，在确定是易支付后，直接google搜索zfaka的易支付接口文件套用就可以了，实测易支付的接口文件适用于新的码支付，太感谢您的提醒了，真是一语道破！
