### ISSUE TITLE
安装完成后前台后台都是404

### ISSUE THREAD

**Issue by fxd2006** [zfaka-plus/zfaka#267]
宝塔环境 LNMP php7.2
先一键部署的1.4.3 前后台都是404 
后又尝试自行安装1.4.5  依然都是404 
伪静态，路径这些都检查过没有问题
同服务器还有2个wordpress网站，不是和这个有冲突吧？

![1 4 5](https://user-images.githubusercontent.com/11625036/158055008-1dd6eb8b-0efb-4027-b127-a840e4ccc843.jpg)
![pub](https://user-images.githubusercontent.com/11625036/158055011-ab8af954-8f27-405f-9aff-47137e5fe5d9.jpg)
![rewrite](https://user-images.githubusercontent.com/11625036/158055012-5594e768-b594-479d-9347-2094ba1c025d.jpg)

**Comment by WishMelz** [comment]
你一开始 设置的 `php change.php Youdir`  做个Youdir才是后台地址

**Comment by fxd2006** [comment]
> 

设置是对的 我用设置的dir后台地址访问也是404   https://www.dogedoge.cc/Meowmeow
