### ISSUE TITLE
能出一个windows下的配置教程么

### ISSUE THREAD

**Issue by Montage-LSM** [zfaka-plus/zfaka#31]
1.3.6版本/res下面少很多文件。

**Comment by Montage-LSM** [comment]
1.3.7版本，/res下面没有layui文件夹，没有对应的JS

**Comment by zlkbdotnet** [comment]
你肯定是弄错了

**Comment by zlkbdotnet** [comment]
1.windows不适合自动安装，所以，手工修改的地方会比较多；不适合小白操作；
2.linux更适合自动安装，你看，我都出了教程，但还是一堆人搞不定；

所以，windows下，就不建议小白折腾了；当然，你可以自己再学一下运维知识，基本windows下就可以搞定．其实很简单
